# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

# 关键：同步环境变量到 dbus 和 systemd，解决 GTK 软件启动慢或权限问题
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waybar & dunst
exec-once =fcitx5 -d --replace
exec-once = bash /home/zi/scripts/wallpaper-picker.sh 
exec-once = nm-applet --indicator

$lock_cmd = swaylock -f -i /home/zi/Pictures/Wallpapers/wallhaven-3q5g5v.jpg

exec-once = swayidle -w \
    timeout 300 '$lock_cmd' \
    timeout 600 'hyprctl dispatch dpms off' \
    resume 'hyprctl dispatch dpms on' \
    before-sleep '$lock_cmd'

bindl=, switch:on:Lid Switch, exec, $lock_cmd


$mainMod = SUPER
$terminal = ghostty
$fileManager = nemo
$menu = wofi



# For moving focus
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, Tab, cyclenext

# K for kill window, V for floating, F for Fullscreen (and back),
# T for terminal, X for menu (like emacs), E for Explorer
bind = $mainMod, K, killactive,
bind = $mainMod, V, togglefloating,
bind = $mainMod, F, fullscreen,
bind = CTRL ALT, T, exec, $terminal
bind = $mainMod, T, exec, $terminal
bind = $mainMod, X, exec, $menu
bind = $mainMod, E, exec, $fileManager

# Q for quit.
bind = $mainMod, Q, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

# Swap between windows
bind = $mainMod ALT, left, movewindow, l
bind = $mainMod ALT, right, movewindow, r
bind = $mainMod ALT, up, movewindow, u
bind = $mainMod ALT, down, movewindow, d

# For resize
bind = $mainMod, R, submap, resize
submap = resize
    binde = , right, resizeactive, 10 0
    binde = , left, resizeactive, -10 0
    binde = , up, resizeactive, 0 -10
    binde = , down, resizeactive, 0 10

    binde = , L, resizeactive, 10 0
    binde = , H, resizeactive, -10 0
    binde = , K, resizeactive, 0 -10
    binde = , J, resizeactive, 0 10

    bind = , escape, submap, reset
    bind = , enter, submap, reset
submap = reset


# Switching between workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 0

# Moving current window among workspaces
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 0


# Super + L (Lock) 
bind = $mainMod, L, exec, $lock_cmd
# bind = $mainMod, L, exec, swaylock -f -c 000000
# bind = $mainMod, L, exec, notify-send "Lock" "Super+L pressed"


# for background blur
decoration {
    blur {
    enabled = false
    size = 3
    passes = 1
    }
}

# For screen Capture
bind = , Print, exec, grim -g "$(slurp)" - | swappy -f -
bind = CTRL, Print, exec, grim - | wl-copy && notify-send "Screenshot" "Fullscreen captured"

# Disable scaling
xwayland {
  force_zero_scaling = true
}